### PR TITLE
Fix the documentation generation

### PR DESCRIPTION
**Pull request by andreaTP**
Instead of hacking more the container build I have attempted to bump everything to a more modern version, and it works 🙂 

Removed most of the hacks for `mkdocs`, and restructured the files/folders to match a working configuration.

I haven't been able to see artifacts created in the Apicurio Registry instance using the' docker-compose' mode though ... cc. @aljesusg

### CODE REVIEW

**Comment by andreaTP** [comment]
please @renjingxiao and @Amoncy try out these changes locally and confirm that everything works.

**Comment by andreaTP** [comment]
Fix #40

**Comment by renjingxiao** [comment]
Hi @andreaTP , I have fetched the branch and tested it locally. It runs well on my side. Thank you for your assistance!

**Comment by andreaTP** [comment]
Tested with @Amoncy and it works as expected 👍

**Pull request merged**
