### PR TITLE
Update Backstage Catalog

### PR DESCRIPTION
**Pull request by Amoncy**
Hi Paolo,

I have added some changes in the Apicurio Registry Component specifically in Descriptions and Links. I am adding the same in other components as well.
Please review the changes and let me know if any changes are required.

Thank you

### CODE REVIEW

**Comment by andreaTP** [comment]
For no specific reason, we have merged another PR touching the same file #26 , I think that the intent and outcome should be similar.
Please let us know if want to iterate on the content with this PR or if you prefer to close it.

**Comment by paoloantinori** [comment]
@paoloantinori

**Comment by Amoncy** [comment]
> For no specific reason, we have merged another PR touching the same file #26 , I think that the intent and outcome should be similar. Please let us know if want to iterate on the content with this PR or if you prefer to close it.

I was thinking of rebasing this code and editing the description as per my understanding , add some missing links and will commit again.

**Review by paoloantinori — APPROVED** [review]
LGTM

**Pull request merged**
