### PR TITLE
User profile

### PR DESCRIPTION
**Pull request by renjingxiao**
HI @andreaTP and @paoloantinori ,

I have added github usernames, jira usernames and rover links to address the issue #29 .
I appreciate your time in reviewing my changes.

Regards

### CODE REVIEW

**Comment by paoloantinori** [comment]
Thanks for the PR @renjingxiao . 

Does this PR impacts directly the visualization of the data on Backstage?
If so could you add screenshots to the PR so the "see" what are gonna be the impact of your work?

**Comment by renjingxiao** [comment]
Sure! Here is the screenshot of the user profile page.
Screenshot 2023-07-24 at 11 10 31

**Comment by paoloantinori** [comment]
Great. This is good!

To make it an additional teaching moment, I'd like you to please "squash" your commits into a single one (since in this case, your PR could be condensed into a single logical unit of work, even if you did this in 4 independent commits.

This link describes the topic, but I'm not sure if there aren't better or simple explanation out there.

The goal is that you will update this PR so that your work will be presented as a single commit:

https://thoughtbot.com/blog/git-interactive-rebase-squash-amend-rewriting-history

**Comment by renjingxiao** [comment]
Thank you so much for your guidance! I've squashed my commits into a single one and updated the PR. Please have a look when you have a moment.

**Pull request merged**
